# Much more here:
# https://www.appveyor.com/docs/appveyor-yml/

# Personally, I try to abstract as much
# out of the yaml as possible.  Makes it
# more portable, less likely to break if
# AppVeyor makes a change to their syntax

environment:
  some_data: blah!
  some_password:
    secure: bJPGwaBN0Km+Ef91ANn5kQ==

# version format
version: 1.0.{build}

# Skip on updates to the readme.
# We can force this by adding [skip ci] or [ci skip] anywhere in commit message
skip_commits:
  message: /updated readme.*|update readme.*s/

# See http://help.appveyor.com/discussions/questions/2433-list-of-os-images
image: Visual Studio 2015

# You can run other stages, but I tend to bundle
# everything into a portable script...
test_script:
  - ps: . .\build.ps1
